# Generated by Django 4.1.1 on 2022-09-10 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sala', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='equipamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='agendamento.equipamento'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='periodo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='agendamento.periodo'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='sala',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='agendamento.sala'),
            preserve_default=False,
        ),
    ]
