# Generated by Django 4.1.1 on 2022-09-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0003_remove_responsavel_materia_responsavel_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsavel',
            name='telefone',
            field=models.CharField(max_length=12),
        ),
    ]
