# Generated by Django 4.1.1 on 2022-09-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0006_alter_responsavel_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsavel',
            name='telefone',
            field=models.CharField(max_length=12),
        ),
    ]
