# Generated by Django 4.1.1 on 2022-09-12 19:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0007_alter_responsavel_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsavel',
            name='senha',
            field=models.CharField(default=123, max_length=20, validators=[django.core.validators.MinLengthValidator(8)]),
            preserve_default=False,
        ),
    ]
