# Generated by Django 4.1.1 on 2022-09-12 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0008_responsavel_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsavel',
            name='senha',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8, 'the field must contain at least 50 characters')]),
        ),
    ]
