# Generated by Django 4.1.1 on 2022-09-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0009_alter_responsavel_senha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsavel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='responsavel',
            name='senha',
        ),
        migrations.AddField(
            model_name='responsavel',
            name='matricula',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
