# Generated by Django 4.1.1 on 2022-09-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0010_remove_responsavel_email_remove_responsavel_senha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsavel',
            name='senha',
            field=models.CharField(default=1234, max_length=20),
            preserve_default=False,
        ),
    ]
