# Generated by Django 4.1.1 on 2022-09-20 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agendamento', '0013_remove_agendamento_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsavel',
            name='matricula',
        ),
        migrations.RemoveField(
            model_name='responsavel',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='responsavel',
            name='telefone',
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agendamento.responsavel'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='nome',
            field=models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
