# Generated by Django 4.1.1 on 2022-09-20 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agendamento', '0014_remove_responsavel_matricula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsavel',
            name='nome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
