# Generated by Django 4.1.1 on 2022-09-20 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agendamento', '0015_alter_responsavel_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
