# Generated by Django 4.1.1 on 2022-10-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0016_alter_agendamento_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='ativo',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
