# Generated by Django 4.1.1 on 2022-10-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0017_equipamento_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='ativo',
            field=models.BooleanField(default=1),
        ),
    ]
